import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";

// 初始化 Inter 字体
const inter = Inter({ 
  subsets: ['latin'],  // 加载拉丁字符集
  // 可选配置
  // weight: ['400', '700'],  // 指定字重
  // display: 'swap',         // 字体显示策略
  // variable: '--font-inter',   // CSS 变量名
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body
        className={`${inter.className} antialiased h-full`}
      >
        {children}
      </body>
    </html>
  );
}
